### ISSUE TITLE
Repeated/Non-descriptive breadcrumbs

### ISSUE THREAD

**Issue by pnolan89** [AdobeDocs/aep-mobile-sdkdocs#113]
Issue in /src/pages/documentation/getting-started/set-up-schemas-and-datasets.md (<--- Not just this page in particular, but it's a good case study)

There are two "Documentation" breadcrumbs in the new Mobile SDK docs. For many docs, based on the breadcrumbs and title alone it can be unclear that these are Mobile SDK docs at all:

![Screen Shot 2022-10-28 at 9 38 58 AM](https://user-images.githubusercontent.com/44183179/198689087-39ab6931-dfa8-4ab1-a88b-d5c56c4a4966.png)

Suggest that one of the "Documentation" breadcrumbs should be "Platform Mobile SDK" or something similar.

**Comment by calebk1** [comment]
Thanks @pnolan89 for the issue!

This seems to be more an issue with the styling of the site, rather than an issue that we (the docs side) can fix. As a result, I'm tracking this under the Developer Site repo under DEVSITE-590.

**Comment by emdobrin** [comment]
This issue has been resolved and "Documentation" is shown only once.
