### ISSUE TITLE
Missing tabs for Core extensions

### ISSUE THREAD

**Issue by emdobrin** [AdobeDocs/aep-mobile-sdkdocs#118]
Mobile Core Signal and Lifecycle documentation has only Android, iOS (AEP 3.x) and iOS (ACP 2.x) tabs, missing the rest.

**Comment by calebk1** [comment]
I don't think this is an issue any more, as I see them on the site:

https://developer.adobe.com/client-sdks/documentation/mobile-core/signal/api-reference/
https://developer.adobe.com/client-sdks/documentation/mobile-core/lifecycle/api-reference/
