### ISSUE TITLE
Missing tabs for getting started section

### ISSUE THREAD

**Issue by emdobrin** [AdobeDocs/aep-mobile-sdkdocs#119]
Getting started section has the following tabs migrated: Android, iOS (AEP) and iOS (ACP), missing Flutter and React Native (ACP) and others. Ref - https://github.com/AdobeDocs/aep-mobile-sdkdocs/pull/20#discussion_r945339047

**Comment by emdobrin** [comment]
@calebk1 if this is still an issue, I will let you decide if you want to add the content to the ACP section directly, but we will still need placeholder tabs for RN and flutter in this repo.

**Comment by calebk1** [comment]
This is no longer an issue, as I added this as part of another PR. For tracking, I'll make a JIRA ticket on that instead.
