### ISSUE TITLE
Unable to navigate to mobile core sections

### ISSUE THREAD

**Issue by emdobrin** [AdobeDocs/aep-mobile-sdkdocs#127]
Unable to navigate to any of the mobile core sections. 
E.g. Mobile Foundation extensions -> Mobile Core -> Lifecycle -> metrics
https://developer-stage.adobe.com/client-sdks/documentation/mobile-core/

**Comment by hbhandal80** [comment]
Unable to replicate the issue, seems to be resolved. Closing.
