### ISSUE TITLE
[Campaign] Update "Set up local notifications" section to follow the latest Android recommendation 

### ISSUE THREAD

**Issue by yangyansong-adbe** [AdobeDocs/aep-mobile-sdkdocs#159]
Google Play docs give the recommendation to fix the Intent vulnerability as below. 
 https://support.google.com/faqs/answer/9267555?hl=en
We should follow the recommendation and update our docs => https://developer.adobe.com/client-sdks/documentation/adobe-campaign-standard/tabs/#set-up-local-notifications

**Comment by rymorale** [comment]
pr: https://github.com/AdobeDocs/aep-mobile-sdkdocs/pull/273
