### ISSUE TITLE
Improve Lifecycle docs

### ISSUE THREAD

**Issue by emdobrin** [AdobeDocs/aep-mobile-sdkdocs#194]
Improve docs for Lifecycle and Lifecycle for Edge Network and explain the difference between calling the Lifecycle APIs in code level vs adding the Data Collection rules with Foreground & Background.
Clarify that the implementation of the APIs is required for lifecycle metrics collection.

**Comment by kevinlind** [comment]
Resolved as part of:
https://github.com/AdobeDocs/aep-mobile-sdkdocs/pull/582
https://github.com/AdobeDocs/aep-mobile-sdkdocs/pull/568
