### ISSUE TITLE
Fix Rules Engine reference to ACPCore

### ISSUE THREAD

**Issue by cdhoffmann** [AdobeDocs/aep-mobile-sdkdocs#195]
Issue in /src/pages/documentation/mobile-core/rules-engine/index.md

"The Rules Engine is provided by the Adobe Experience Platform Mobile SDKs as part of the [MobileCore (Android)/ACPCore (iOS)](https://developer-stage.adobe.com/client-sdks/documentation/mobile-core/) extension."

We should change this to reference AEPCore potentially or some other terminology like "as part of the latest Core for both iOS and Android"

**Comment by cdhoffmann** [comment]
@calebk1 I'm gonna go ahead and fix this reference with the other issues i found.

**Comment by calebk1** [comment]
Yup! Sounds good to me.

**Comment by cdhoffmann** [comment]
Fixed in #210
