### ISSUE TITLE
Configuration API References fixes

### ISSUE THREAD

**Issue by cdhoffmann** [AdobeDocs/aep-mobile-sdkdocs#199]
Issue in /src/pages/documentation/mobile-core/configuration/api-reference.md

1. Under the "clearUpdatedConfiguration" section, there is an info note which says "This API is only available in Android and iOS." which should be removed.
2. Under the "configureWithFileInAssets" section, the info note should be updated to remove reference to old Android versions
3. Under the "configureWithFileInPath" section, the link titled "Configure with App ID per environment" doesn't do anything. Not sure if that's just because the link leads to the section above? The same thing happens for the next link down

**Comment by cdhoffmann** [comment]
@calebk1 Do you know how to fix #3 on here?

**Comment by prudrabhat** [comment]
@cdhoffmann - I will fix the link with my PR. The fix is to change the link format from `[Configure with App ID per environment](./index.md#configure-with-app-id-per-environment) approach`  to.  `[Configure with App ID per environment](#configure-with-app-id-per-environment) approach.`

**Comment by cdhoffmann** [comment]
Thank you! @prudrabhat

**Comment by cdhoffmann** [comment]
It's actually broken in multiple places on that page

**Comment by cdhoffmann** [comment]
Fixed in #209
