### ISSUE TITLE
locationClicked -> clickedLocation

### ISSUE THREAD

**Issue by matt-adler** [AdobeDocs/aep-mobile-sdkdocs#203]
Looks like you renamed `locationClicked` to `clickedLocation` for Java

### Expected Behaviour
documentation that matches sdk
### Actual Behaviour
Java was different, but I guess is no longer 👍, so update your docs.

**Comment by swarna04** [comment]
@matt-adler Thank you for pointing it out. We are aware of this and we are currently working on updating our documentation for the latest Android SDKs upgrade. You should see the doc changes published and released soon.

**Comment by praveek** [comment]
@matt-adler https://developer.adobe.com/client-sdks/documentation/adobe-target/api-reference/#clickedlocation
