### ISSUE TITLE
Adobe Target - Visual Preview

### ISSUE THREAD

**Issue by SydneeChristensen** [AdobeDocs/aep-mobile-sdkdocs#258]
Issue in /src/pages/documentation/adobe-target/index.md

A couple of consultants set up visual preview with the AEP mobile SDK with the Target extension for the first time. They found that target.previewEnabled isn't enabled by default with the AEP mobile SDK. So for the visual preview to work the user will need to enable it. Should look something like 
`MobileCore.updateConfigurationWith(configDict: ["target.previewEnabled": true]) //preview for target`
Can we add this step to this documentation?

**Comment by swarna04** [comment]
Thanks @SydneeChristensen. I discovered this today while working with a consultant. I suppose we will need to make a fix for this in the AEPTarget SDK as preview should be enabled by default similar to ACPTarget SDK.

**Comment by SydneeChristensen** [comment]
@swarna04 should we make the change to the SDK instead of the documentation then?

**Comment by swarna04** [comment]
Yes, we should update the latest Target SDK. Meanwhile, folks can use the workaround of enabling it explicitly via updateConfiguration API like you mentioned above.
