### ISSUE TITLE
iOS lifecycle metrics section still referencing ACP

### ISSUE THREAD

**Issue by cdhoffmann** [AdobeDocs/aep-mobile-sdkdocs#278]
Issue in [/src/pages/documentation/getting-started/enable-debug-logging.md 
](https://developer.adobe.com/client-sdks/documentation/getting-started/enable-debug-logging/)
In the Lifecycle Metrics section we reference ACP APIs.

**Comment by emdobrin** [comment]
@calebk1 @cdhoffmann can we get this one resolved since the ACP version is now deprecated?
