### ISSUE TITLE
How to implement adobe analytics on expo managed project 

### ISSUE THREAD

**Issue by MarKamenov** [AdobeDocs/aep-mobile-sdkdocs#289]
Is it possible to integrate adobe analytics in the mobile app which is built using react native expo managed project.
Expo's config plugins help changing native code, but there is no guidance how to create config plugin and implement analytics on expo managed project.

**Comment by yangyansong-adbe** [comment]
@MarKamenov I created a duplicate issue (https://github.com/adobe/react-native-acpanalytics/issues/78) on the related repository, so close this issue.
