### ISSUE TITLE
[ACC] Add correct iOS/ Android install instructions

### ISSUE THREAD

**Issue by swarna04** [AdobeDocs/aep-mobile-sdkdocs#37]
### Expected

https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-campaignclassic#add-campaign-classic-to-your-app

### Actual

https://developer-stage.adobe.com/client-sdk/documentation/adobe-campaign-classic/#add-campaign-classic-to-your-app

**Comment by calebk1** [comment]
This will be fixed in #89!
