### ISSUE TITLE
Updates for  Mobile Services

### ISSUE THREAD

**Issue by emdobrin** [AdobeDocs/aep-mobile-sdkdocs#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://developer.adobe.com/client-sdks/previous-versions/documentation/upgrade-platform-sdks/comparison/

### What's wrong with the content?

For the Mobile Services sunset, update user guides, FAQs or other references to Mobile Services extension and indicate the migration options for each feature.
If the same guide exists in previous-versions, update accordingly.

e.g. 
https://developer.adobe.com/client-sdks/documentation/faq/
https://developer.adobe.com/client-sdks/documentation/upgrade-platform-sdks/comparison/

**Comment by yangyansong-adbe** [comment]
The PR (https://github.com/AdobeDocs/aep-mobile-sdkdocs/pull/529) was merged into the staging branch. The changes will be deployed alongside other updates for Android 3.0 release.
cc @emdobrin @ahmyr @praveek
