### ISSUE TITLE
[ACC] Configuration keys issues

### ISSUE THREAD

**Issue by swarna04** [AdobeDocs/aep-mobile-sdkdocs#39]
1. Configuration API reference link points to gitbook

I see `FIX LINK` under the section, probably that's a cue to fix the link at some point.
<img width="811" alt="Screen Shot 2022-08-09 at 2 51 43 PM" src="https://user-images.githubusercontent.com/13000319/183768462-6d4df43b-2b4f-4bac-ac60-01eb83d46b26.png">

2. Remove environment prefixed keys as Configuration is environment aware
Find expected Configuration key list here https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-campaignclassic#configuration-keys

**Comment by calebk1** [comment]
This will be fixed as part of #89!
