### ISSUE TITLE
[ACC] May 2022 iOS/ Android release notes are missing

### ISSUE THREAD

**Issue by swarna04** [AdobeDocs/aep-mobile-sdkdocs#40]
Please include the below releases in the release notes
https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-campaignclassic/adobe-campaign-classic-release-notes#may-18-2022
https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-campaignclassic/adobe-campaign-classic-release-notes#may-17-2022

**Comment by calebk1** [comment]
This has already been done!
