### ISSUE TITLE
[ACC] Formatting is off in iOS (ACP 2.x) objC example for tracknotificationClick API

### ISSUE THREAD

**Issue by swarna04** [AdobeDocs/aep-mobile-sdkdocs#41]
[tracknotificationclick](https://developer-stage.adobe.com/client-sdk/documentation/adobe-campaign-classic/api-reference/#tracknotificationclick)
<img width="726" alt="Screen Shot 2022-08-09 at 5 26 13 PM" src="https://user-images.githubusercontent.com/13000319/183784287-4b01cfe7-d423-4039-b1e7-76264072088b.png">

**Comment by calebk1** [comment]
I think this has already been fixed? If it's not correctly formatted, please re-open this issue!
