### ISSUE TITLE
[ACS] Release notes are not updated for Android v1.0.9 and iOS v3.0.1 releases

### ISSUE THREAD

**Issue by swarna04** [AdobeDocs/aep-mobile-sdkdocs#44]
Release notes are available on sdk docs.
https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-campaign-standard/adobe-campaign-standard-release-notes#may-27-2022
https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-campaign-standard/adobe-campaign-standard-release-notes#february-9-2022

**Comment by calebk1** [comment]
This has already been done!
