### ISSUE TITLE
[ACS] registerExtension(s) API

### ISSUE THREAD

**Issue by swarna04** [AdobeDocs/aep-mobile-sdkdocs#45]
These are Mobile Core APIs, see https://aep-sdks.gitbook.io/docs/foundation-extensions/mobile-core/mobile-core-api-reference#registerextension-s

iOS (3.x)
static func registerExtensions(_ extensions: [NSObject.Type], 
                               _ completion: (() -> Void)? = nil)

iOS (1.x)
+(BOOL) registerExtension: (nonnull Class) extensionClass
                     error: (NSError* _Nullable* _Nullable) error;

The first two tabs here https://developer-stage.adobe.com/client-sdk/documentation/adobe-campaign-standard/migration/#registerextension contain the invocation example whereas the last one for iOS 1.x contains incorrect syntax. Let's fix it.
<img width="793" alt="Screen Shot 2022-09-01 at 11 01 27 AM" src="https://user-images.githubusercontent.com/13000319/187982673-c3fcc3bc-bd4f-4cac-ba86-7fb0f8b0c2bd.png">

We should also point to the Mobile Core documentation for correct syntax and additional details.

Note: The issue is present in gitbook as well - https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-campaign-standard/migration#registerextension

**Comment by calebk1** [comment]
@swarna04 If we could pick this up directly in a PR (since this area has been properly migrated over now), that would be easier!
