### ISSUE TITLE
[ACS] Event reference - Configuration response issue

### ISSUE THREAD

**Issue by swarna04** [AdobeDocs/aep-mobile-sdkdocs#47]
The Configuration response no longer contains environment specific keys, as opposed to what's listed here - https://developer-stage.adobe.com/client-sdk/documentation/adobe-campaign-standard/event-reference/#payload-definition-1

The list needs to be updated on extension main page as well - https://developer-stage.adobe.com/client-sdk/documentation/adobe-campaign-standard/#configuration-keys

Note: This issue is present and needs to be fixed in gitbook as well - https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-campaign-standard/adobe-campaign-standard-event-reference#configuration-response, https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-campaign-standard#configuration-keys

**Comment by calebk1** [comment]
@swarna04 If this needs to be fixed in Gitbook as well, I think creating a PR to address directly would be a more effective course of action. 

As a result, I'm going to close this issue, with the intention that this will be done as a PR instead. If that's not acceptable, please re-open this issue!
