### ISSUE TITLE
[ACS] [iOS] Syntax/ examples for AEP 3.x and ACP 1.x 

### ISSUE THREAD

**Issue by swarna04** [AdobeDocs/aep-mobile-sdkdocs#48]
Objective C syntax for AEP 3.x and Swift syntax for ACP 1.x are available on gitbook, however they are not updated in the port here https://developer-stage.adobe.com/client-sdk/documentation/adobe-campaign-standard/api-reference/

**Comment by calebk1** [comment]
This has been done already!

https://developer.adobe.com/client-sdks/documentation/adobe-campaign-standard/api-reference/
