### ISSUE TITLE
[ACS] Main page - top of the page warnings

### ISSUE THREAD

**Issue by swarna04** [AdobeDocs/aep-mobile-sdkdocs#52]
I think we can get rid of the beta warning for ACS extension now

<img width="842" alt="Screen Shot 2022-09-01 at 12 19 16 PM" src="https://user-images.githubusercontent.com/13000319/187995239-5971b59d-1404-444c-9543-4745027b3306.png">

Note: This needs to be fixed in gitbook as well https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-campaign-standard

**Comment by calebk1** [comment]
This will be completed in #120 !
