### ISSUE TITLE
[Analytics] Issues on the main page

### ISSUE THREAD

**Issue by cacheung** [AdobeDocs/aep-mobile-sdkdocs#55]
https://developer-stage.adobe.com/client-sdk/documentation/adobe-analytics/
New content has been updated in gitbook, some content is outdated.  Listing the issues I saw below:

1. Missing a line break after Configure the Analytics extension in the Data Collection UI

![UI_Issue](https://user-images.githubusercontent.com/29806547/190076506-35a4e5c1-3247-4e1d-831a-a9949ae4ec98.png)

2. Missing iOS (3.x), Xarmarin in the Tabs (Add Analytics to your application, Register Analytics with Mobile Core, Event serialization, Update Analytics configuration) for this main page.  Note, Unity is deprecated. Do we still want to keep it there?
Are we keeping iOS (2.x) in this doc?

3. Most of the links in this pages are linking to GitBook.  They should be linked to this repo. 4. 
e.g Mobile Core, setApplication(), Lifecycle metrics, trackState, trackAction, configuration API reference...

4. The code samples are not in the correct format.  (Please check all the tabs sections)

E.g.
![Miss3 xTab](https://user-images.githubusercontent.com/29806547/190080559-36359d79-39ae-49a3-a074-468971a3001d.png)

5. Should have Swift Sample first, then Objective-C (can we match what we have in Gitbook?)
e.g. 
![swift_objectiveC_order](https://user-images.githubusercontent.com/29806547/190081827-75c8a605-2dcd-46f8-ab4d-f087f3b3002d.png)

6. The video in "The following video shows you how to use trackState APIs to send data to Adobe Analytics" is not accessible.  The one in GitBook is outdated (it was use iOS ACP as an example).  I think we can remove it. I will discuss with the team and come back.

![video](https://user-images.githubusercontent.com/29806547/190084696-a52247fc-fbed-4390-8cdd-055908689188.png)

**Comment by calebk1** [comment]
Most of these issues have been resolved, except 1 and 6.

For 6, have you gotten confirmation that the video can be removed?

For 1, it's a rendering issue with the site, and I'll file a bug for that.

cc: @cacheung

**Comment by emdobrin** [comment]
For no 1 we will keep the internal task open. Other than that, the other items have been resolved.
