### ISSUE TITLE
[Analytics] Issues on API reference

### ISSUE THREAD

**Issue by cacheung** [AdobeDocs/aep-mobile-sdkdocs#56]
Issues In the page https://developer-stage.adobe.com/client-sdk/documentation/adobe-analytics/api-reference/

1. Missing Unity and Xamarin tabs.  (Unity is deprecated, Xamarin is not)
e.g 
<img width="1101" alt="missingtabs" src="https://user-images.githubusercontent.com/29806547/190085447-0c081ecc-f32b-42bd-9511-c41e265bf3bf.png">

2. Swift and Objective order for ACP2.x.  In GitBook, we have Swift first, then Objective-C
e.g.
<img width="828" alt="ACP2 xOrder" src="https://user-images.githubusercontent.com/29806547/190086365-d79ab82c-b2d6-4e01-bdb6-8dd55af64e28.png">

4. extensionVersion API is missing syntax
e.g 
<img width="820" alt="extensionVersionAPI" src="https://user-images.githubusercontent.com/29806547/190086471-15e0be88-fca3-4ac7-b9e1-209888c9d759.png">

5. Missing Objective-C syntax in iOS(AEP 3.x) and missing Swift syntax in iOS(ACP 2.x).  They were updated in the latest GitBook
e.g. 
<img width="824" alt="Screen Shot 2022-09-13 at 5 38 55 PM" src="https://user-images.githubusercontent.com/29806547/190087104-9d0def0d-43ee-44b4-a8fd-7c1eb9851f1a.png">

6. Broken links
MobileCore.resetIdentities
https://developer-stage.adobe.com/client-sdk/documentation/foundation-extensions/mobile-core/mobile-core-api-reference.md#resetidentities
Should be
https://developer-stage.adobe.com/client-sdk/documentation/mobile-core/api-reference/#resetidentities

setVisitorIdentifier links to GitBook, it should link to this doc

7. getTrackingIdentifierWithCompletionHandler, need to add 
Starting with v1.2.9 (Android) / v3.0.3(iOS AEPAnalytics) / v2.5.1 (iOS ACPAnalytics) this API does not generate or retrieve a new tracking identifier (AID) for new visitors.....warning block at in the GitBook

8. sendQueuedHits API has no content under iOS(AEP3.x) and the tabs next to it.
<img width="834" alt="sendQueueHits" src="https://user-images.githubusercontent.com/29806547/190090980-f9adfb98-810b-4b18-85a3-e7aa50d05410.png">

**Comment by calebk1** [comment]
All these issues have already been resolved!
