### ISSUE TITLE
[Analytics] Issues in Event reference, Migrating, Product variable, Release Notes and FAQ pages

### ISSUE THREAD

**Issue by cacheung** [AdobeDocs/aep-mobile-sdkdocs#57]
Issue in https://developer-stage.adobe.com/client-sdk/documentation/adobe-analytics/event-reference/

1. Links are pointing to GitBook.  They should be pointed to this repo
trackAction, tractState, sendQueuedHits, clearQueue, getQueueSize, getTrackingIdentifier and getCustomVisitorIdentifier, lifecycleStart() with null context data...

Issue in https://developer-stage.adobe.com/client-sdk/documentation/adobe-analytics/migration/
2. Text format in Migration AEPAnalytics
<img width="802" alt="migration" src="https://user-images.githubusercontent.com/29806547/190095077-fd967154-6f48-4c40-9d5d-2606ff492986.png">

Issue in https://developer-stage.adobe.com/client-sdk/documentation/adobe-analytics/product-variable/
3. There is no AEP(3.x) and ACP(2.x) tags

4. Remove "A sample network request can be seen in the image below:"  It is no longer in GitBook.
<img width="840" alt="removeGraphic" src="https://user-images.githubusercontent.com/29806547/190096363-9e7e2097-ac4e-48bd-98dc-667b02a4add6.png">

5. Need to replace the Manage App Setting's graphic (which is using mobile services UI) to Analytics UI.6. 
![product variable](https://user-images.githubusercontent.com/29806547/190489492-8a99034e-ade5-4da2-b9a4-492fc79b7bc6.png)
Refer to: https://experienceleague.adobe.com/docs/mobile-services/windows-universal-appstore/analytics-win-appstore/products-variable/products.html?lang=en

6. https://developer-stage.adobe.com/client-sdk/documentation/adobe-analytics/release-notes/
Need to be updated.

7. Missing Frequently asked questions.  (This FAQ is newly added)
https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-analytics/analytics-faq

**Comment by calebk1** [comment]
Dealing with this in #120!
