### ISSUE TITLE
[Media Analytics] Issues on main page

### ISSUE THREAD

**Issue by cacheung** [AdobeDocs/aep-mobile-sdkdocs#58]
https://developer-stage.adobe.com/client-sdk/documentation/adobe-media-analytics/#configure-media-analytics-extension

1. Need a line break before the steps.
<img width="813" alt="line break" src="https://user-images.githubusercontent.com/29806547/190517026-1ae69b4f-677a-4005-bf71-ba59dfe7946e.png">

2. Need to fix the version link graphics
<img width="848" alt="link" src="https://user-images.githubusercontent.com/29806547/190517172-750ff93a-6972-4a88-980d-f5e4c4b3ce91.png">

![link2](https://user-images.githubusercontent.com/29806547/190533378-3df9cc3f-2a1f-45cd-a7aa-f7b5fcfa0176.png)

3. There is no iOS(3.x) and iOS(2.x) separation tabs.  (The content in GitBook has updated, need to get the latest from there)

4. Some links is pointing to GitBook.  It should be linked to developer.adobe.com content.
e.g [Configuration API reference](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/mobile-core/configuration/configuration-api-reference).

**Comment by calebk1** [comment]
All these issues have been fixed!
