### ISSUE TITLE
Android SDK release notes are late on every release

### ISSUE THREAD

**Issue by PGHM** [AdobeDocs/aep-mobile-sdkdocs#703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

Hey, whenever new Android BOM version is released (at the time of writing this it is 3.4.0) the release notes page https://developer.adobe.com/client-sdks/home/release-notes/ is not updated and we cannot check what has changed. It updates at some point, but it is inconvenient. Could you publish the changelog at the same you publish the BOM updates?

**Comment by praveek** [comment]
Thanks for bringing this to our attention. The release notes for BOM 3.4.0 is now [live](https://developer.adobe.com/client-sdks/home/release-notes/#android-bom-340). Moving forward, we’ll ensure the documentation stays in sync with the releases.
