### ISSUE TITLE
[Troubleshooting guides] Listed issues based on review

### ISSUE THREAD

**Issue by emdobrin** [AdobeDocs/aep-mobile-sdkdocs#74]
https://developer-stage.adobe.com/client-sdk/documentation/troubleshooting-guides/

**index.md**
1. Update link title to: `Troubleshooting Campaign push notifications`

**push-messaging.md**
1. The info block contains two links to the same page, remove the first one and just keep the one for `see the documentation`.
2. Steps have inconsistent ending punctuation, should use period at the end of each step. 

![Screen Shot 2022-09-29 at 11 25 24 AM](https://user-images.githubusercontent.com/33132425/193113205-4e12a0c3-852d-4e2a-be81-7340f97d40e8.png)

3. Tabs content not displaying correctly for setPushIdentifier. I suggest linking to the setPushIdentifier API 
![Screen Shot 2022-09-29 at 11 33 46 AM](https://user-images.githubusercontent.com/33132425/193114983-41758933-452f-4130-9920-f9af6f16409a.png)

**push-notifications.md**
1. Inconsistent title with other pages and links. `Campaign Push Notifications` should be: `Troubleshooting Campaign push notifications`, left nav should be `Campaign push notifications`.
2. All tabs are broken 
![Screen Shot 2022-09-29 at 11 44 10 AM](https://user-images.githubusercontent.com/33132425/193116421-7c9fb4ab-d30e-45b6-a65f-ce5ce7199846.png)
3. Text missing for first section `To set up server key/APNS server certificate in the Campaign instance, complete the following steps:` + tabs.
4. campaignPush-android.md content is incorrect.

**All files:** 
1. Recommend using inline tabs or only one file for all tabs content.
2. Debate if these troubleshooting guides can be moved under Campaign section cc @swarna04

**Comment by calebk1** [comment]
Done as part of #120! 

That being said, should this be under the Campaign section? @swarna04
