### ISSUE TITLE
[Consent] Listed issues based on review

### ISSUE THREAD

**Issue by emdobrin** [AdobeDocs/aep-mobile-sdkdocs#75]
Review on https://developer-stage.adobe.com/client-sdk/documentation/consent-for-edge-network/

**index.md**

1. Broken links:
- First link to Edge Network extension
- Migrate to swift link under Download and import the Consent extension -> ACP 2.x

2. Formatting/indentations in tabs - numbered lists followed by code snippets show incorrectly. Can the number be indentation as the text below or should we remove numbers?
![Screen Shot 2022-09-29 at 10 38 33 PM](https://user-images.githubusercontent.com/33132425/193198294-99b3ea17-f194-496a-b5fe-a443a5d847fc.png)

3. Header underline shows incorrectly for long header names
![Screen Shot 2022-09-29 at 10 41 54 PM](https://user-images.githubusercontent.com/33132425/193198428-88b13483-29b8-43cb-a21e-70c73bb1951a.png)

**Left nav**
1. Should show Release notes first, then API reference

![Screen Shot 2022-09-29 at 10 48 39 PM](https://user-images.githubusercontent.com/33132425/193199244-a06f2fcd-98e5-4d45-8472-a9dea27fbfa5.png)

**Comment by calebk1** [comment]
All of these have been fixed in #120!

3 seems to be an issue with the developer site itself, so I'll file a ticket in their JIRA. As for release notes, I think we've put it at the end for all the other ones, so I'll be leaving it there.
