### ISSUE TITLE
[Audience Manager] Listed issues based on review

### ISSUE THREAD

**Issue by emdobrin** [AdobeDocs/aep-mobile-sdkdocs#77]
Reviewed section https://developer-stage.adobe.com/client-sdk/documentation/adobe-audience-manager/

**index.md**
1. Usages of "click" should be updated to "select"
2. Missing iOS (AEP 3.x) tab in all examples
3. Outdated content in Android and iOS (ACP 2.x) tabs
4. FIX LINK items

**release-notes.md**
1. Missing 2022 release notes

**api-reference.md**
1. Should remove cordova tab.

**event-reference.md**
1. Table content overlaps with right side menu
2. FIX LINKs

General comments:
1. (Tabs content not reviewed) Should collapse the code examples for all tabs in a single file by using variants (see identity for edge network as an example).
2. Left nav items should be ordered as per gitbook:
![Screen Shot 2022-10-03 at 6 39 05 PM](https://user-images.githubusercontent.com/33132425/193716173-dce6e09b-12ab-4a50-bb23-e12e72a1eb49.png)

**Comment by calebk1** [comment]
These have already been fixed!
