### ISSUE TITLE
[Mobile Core Identity] Listed issues based on review

### ISSUE THREAD

**Issue by emdobrin** [AdobeDocs/aep-mobile-sdkdocs#80]
Reviewing https://developer-stage.adobe.com/client-sdk/documentation/mobile-core/identity/

- [x] **index.md**
1. Register the Identity extension -> Flutter tab -> should be "When using Flutter, registering ...
2. Remove Version of the Identity extension (already covered in api-reference)
3. Implementing visitor tracking .. -> all tabs - link to appendVisitorInfoForUrl is broken

- [x] **api-reference.md**
1. Link to Signals extension is broken
2. Tabs content seems out of date for some API, for example appendToUrl, extensionVersion ACP 2.x tab shows Swift content first, followed by objc. Other content may be outdated as well, to revisit.

- [x] **event-reference.md**
1. Link to [Mobile Core Configuration event reference](https://developer-stage.adobe.com/client-sdk/documentation/mobile-core/configuration/event-reference/) points to empty page.
2. Shared state -> visitoridslist Type should be simply List.

- [x] **General**
1. Remove cordova tab from all code snippets
3. FIX LINKs
4. Unable to review tabs content. Todo: reduce files under tabs folder to max 1 file per doc file which includes all tabs for a sample code (using variants)
5. Left nav should be: Migration, API reference, Event reference

**Comment by calebk1** [comment]
@emdobrin These have been fixed in #120!

That being said, Mobile Core configuration is known to be empty (and is empty on Gitbook as well). I asked the dev, and I think they mentioned they will fill it in soon.
