### ISSUE TITLE
[Home] Issues based on review

### ISSUE THREAD

**Issue by spoorthipujariadobe** [AdobeDocs/aep-mobile-sdkdocs#82]
Reviewing: https://developer-stage.adobe.com/client-sdk/documentation/

- [x] Missing subtitle below page heading `Welcome to the home of Adobe Experience Platform Mobile SDK documentation.`

- [x] Good to go for iOS 15 section
1. Heading and content needs to be changed for iOS 16 and Android 13.
2. Link for `current SDK versions` page is wrong

- [x] `Project Griffon will be Assurance` box is missing

- [x] Need to remove following boxes
1. `The Swift versions of the iOS SDKs have been released!`
2. `Support for Adobe Experience Platform Edge Network`

- [x] Are you interested in Kotlin? section
1. Heading and content needs to be changed. Check with Chetan if we still need it as we are already doing a refactor in Kotlin.
2. Needs to be moved after `Supported Platforms section.
3. `following survey` link opens a 404 form. Need to check with Chetan for the updated form link.

- [x] Bring the Adobe Experience Cloud to your apps section - Link for `variety` is incorrect, should point to `Supported Platforms` section in same page

- [x] Embedded video needs to be removed (maybe it was removed because it was outdated?)

- [x] Supported platforms section
1. Missing some entry for React Native AEP 1.x.
2. Links and texts are incorrect, should point to corresponding section in current SDK versions page.

- [x] Resources section
1. Should be places above `Get Help section`
2. Should be renamed as `Quick links`

- [x] Get help
1. Needs to be the last section on the page
2. Needs to renamed to `Further help`
3. Text need to be changed

**Comment by calebk1** [comment]
These are being tracked in #115!

I'll close this issue once that PR is merged in.
