### ISSUE TITLE
[Upgrading to AEP] Issues based on review 

### ISSUE THREAD

**Issue by praveek** [AdobeDocs/aep-mobile-sdkdocs#84]
Reviewing https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep

- [x] https://developer-stage.adobe.com/client-sdks/documentation/upgrade-platform-sdks/comparison/
     -  Last 2 rows are missing links to Places extension (https://developer-stage.adobe.com/client-sdks/documentation/upgrade-platform-sdks/comparison/#adobe-analytics---mobile-services--mobile-add-on )

- [x] https://developer-stage.adobe.com/client-sdks/documentation/upgrade-platform-sdks/manual-lifecycle-implementation/
     - The page is broken

- [x] https://developer-stage.adobe.com/client-sdks/documentation/upgrade-platform-sdks/api-changelog/
    - Some links redirect to GitHub instead of corresponding documentation (https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep/api-change-log#supported-apis)
    - Fix text in https://developer-stage.adobe.com/client-sdks/documentation/upgrade-platform-sdks/api-changelog/#deprecated-apis
    - Fix `trackBeacon:Data  - See Guide` link in https://developer-stage.adobe.com/client-sdks/documentation/upgrade-platform-sdks/api-changelog/#deprecated-apis-and-functionality

- [x] https://developer-stage.adobe.com/client-sdks/documentation/upgrade-platform-sdks/current-sdk-versions/
     - [x] https://developer-stage.adobe.com/client-sdks/documentation/upgrade-platform-sdks/current-sdk-versions/#ios--swift 
        -  Places Monitor should be marked as deprecated 
        -  Change Adobe Journey Optimizer link to https://github.com/adobe/aepsdk-messaging-ios
     - [x] https://developer-stage.adobe.com/client-sdks/documentation/upgrade-platform-sdks/current-sdk-versions/#ios--objective-c
         - Change MobileCore link to https://github.com/Adobe-Marketing-Cloud/acp-sdks/tree/master/iOS/ACPCore 
         - Change Adobe Analytics - Mobile Services link to https://github.com/Adobe-Marketing-Cloud/acp-sdks/tree/master/iOS/ACPMobileServices
- [x] https://developer-stage.adobe.com/client-sdks/documentation/upgrade-platform-sdks/analytics-comparison/#configuration
     - None of the code samples in the page are rendered 
- [x] https://developer-stage.adobe.com/client-sdks/documentation/migrate-to-swift/
     - The following links are broken in https://developer-stage.adobe.com/client-sdks/documentation/migrate-to-swift/#update-api-usage-and-references-for-each-extension 
         - Signal  
         - Assurance
         - Adobe Experience Platform Campaign Classic

**Comment by calebk1** [comment]
Fixing the issues in #120!
