### ISSUE TITLE
[AEP Assurance] [AEP Assurance SDK] Issues based on doc review

### ISSUE THREAD

**Issue by prudrabhat** [AdobeDocs/aep-mobile-sdkdocs#86]
### Issue list for [`Mobile Foundation Extensions` -> `Adobe Experience Platform Assurance`](https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance-sdk/)
1. In the overview page (https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance-sdk/ ) `This extension enables capabilities for Adobe Experience Platform Assurance` is missing link to the [platform-assurance page](https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance/)
2. The sub-section [Import the library to your app code](https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance-sdk/#import-the-library-to-your-app-code) contains content ([link](https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance-sdk/#swift-2) , [link](https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance-sdk/#objective-c-2)) which should be present in `Register AEPAssurance with Mobile Core`  sub-section instead.
3. In subsection [Register AEPAssurance with Mobile Core][https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance-sdk/#register-aepassurance-with-mobile-core] , Android Tab contains [Swift](https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance-sdk/#swift-2) and [Objective-C](https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance-sdk/#objective-c-2) contents which must be removed 
4. [Register AEPAssurance with Mobile Core](https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance-sdk/#register-aepassurance-with-mobile-core) all tabs contains duplicate content for Swift and Objective-c
5. The content in tabs for iOS(AEP 3.x) and iOS (AEP 1.x) in the section [Implement AEP Assurance session start APIs (iOS only)](https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance-sdk/#implement-aep-assurance-session-start-apis-ios-only) is incorrect and does not match [old docs](https://aep-sdks.gitbook.io/docs/foundation-extensions/adobe-experience-platform-assurance#implement-aep-assurance-session-start-apis-ios-only) 
6. Link broken / Page does not get rendered for `Resolving Common Issues`  page. 

### Issue list for [`Adobe Experience Platform Assurance`](https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance/)

1. [General Availability](https://aep-sdks.gitbook.io/docs/adobe-assurance/project-griffon#general-availability) section from original docs is missing in the page.
2. In [QuickSetup](https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance/#quick-setup) missing link to the Adobe Experience Platform Mobile SDK in `....Assurance works with the Adobe Experience Platform Mobile SDK`
3. [Get Access](https://aep-sdks.gitbook.io/docs/adobe-assurance/project-griffon/get-access) page does not exist in new docs. Question: Is this intentionally omitted? 
4. Point 2 in page Custom Validation [Getting Started](https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance/tutorials/custom-validation/#getting-started) has broken links to `Create` and `Connect`
5.  Point 2 in Validation Summary page [Getting Started](https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance/tutorials/validation-summary/#getting-started) has broken links to `Create` and `Connect`
6. In section [Troubleshooting](https://developer-stage.adobe.com/client-sdks/documentation/platform-assurance/tutorials/validation-summary/#troubleshooting) `To learn more about validations, you can visit the Adobe Experience Platform Assurance Validations GitHub` the git hub link is broken and should point to https://github.com/adobe/assurance-validation-plugins

**Comment by calebk1** [comment]
@prudrabhat Almost all of these have been fixed in #120! 

However, the link you provided for the GitHub link is still broken for me. Please advise what link I should use instead. (I'm closing this issue for now, though! Please provide the link in another issue/create a PR yourself to update it.)
